name: Repository Activity Monitor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, closed, reopened]
  pull_request_review:
    types: [submitted]
  discussion:
    types: [created]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate notification message
        id: generate_message
        run: |
          # Set event specific details
          case "${{ github.event_name }}" in
            "push")
              echo "EVENT_DETAILS=Branch: ${{ github.ref_name }}" >> $GITHUB_ENV
              echo "EVENT_DETAILS_COMMIT=Commit: ${{ github.sha }}" >> $GITHUB_ENV
              echo "EVENT_DETAILS_MSG=Message: ${{ github.event.head_commit.message }}" >> $GITHUB_ENV
              ;;
            "pull_request")
              echo "EVENT_DETAILS=PR #${{ github.event.pull_request.number }}" >> $GITHUB_ENV
              echo "EVENT_DETAILS_TITLE=Title: ${{ github.event.pull_request.title }}" >> $GITHUB_ENV
              echo "EVENT_DETAILS_STATE=State: ${{ github.event.pull_request.state }}" >> $GITHUB_ENV
              ;;
            "issues")
              echo "EVENT_DETAILS=Issue #${{ github.event.issue.number }}" >> $GITHUB_ENV
              echo "EVENT_DETAILS_TITLE=Title: ${{ github.event.issue.title }}" >> $GITHUB_ENV
              echo "EVENT_DETAILS_STATE=State: ${{ github.event.issue.state }}" >> $GITHUB_ENV
              ;;
            *)
              echo "EVENT_DETAILS=Event occurred in ${{ github.repository }}" >> $GITHUB_ENV
              ;;
          esac

      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🔔 *New Activity in ${{ github.repository }}*
            
            *Type:* ${{ github.event_name }}
            *Actor:* ${{ github.actor }}
            
            *Details:*
            ${{ env.EVENT_DETAILS }}
            ${{ env.EVENT_DETAILS_COMMIT }}
            ${{ env.EVENT_DETAILS_MSG }}
            ${{ env.EVENT_DETAILS_TITLE }}
            ${{ env.EVENT_DETAILS_STATE }}
            
            [View on GitHub](https://github.com/${{ github.repository }}) 