name: Repository Activity Monitor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, closed, reopened]
  pull_request_review:
    types: [submitted]
  discussion:
    types: [created]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate notification message
        id: generate_message
        run: |
          # Set event specific details
          case "${{ github.event_name }}" in
            "push")
              echo "::set-output name=details::Branch: ${{ github.ref_name }}
              Commit: ${{ github.sha }}
              Message: ${{ github.event.head_commit.message }}"
              ;;
            "pull_request")
              echo "::set-output name=details::PR #${{ github.event.pull_request.number }}
              Title: ${{ github.event.pull_request.title }}
              State: ${{ github.event.pull_request.state }}"
              ;;
            "issues")
              echo "::set-output name=details::Issue #${{ github.event.issue.number }}
              Title: ${{ github.event.issue.title }}
              State: ${{ github.event.issue.state }}"
              ;;
            *)
              echo "::set-output name=details::Event occurred in ${{ github.repository }}"
              ;;
          esac

      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🔔 *New Activity in ${{ github.repository }}*
            
            *Type:* ${{ github.event_name }}
            *Actor:* ${{ github.actor }}
            
            *Details:*
            ${{ steps.generate_message.outputs.details }}
            
            [View on GitHub](https://github.com/${{ github.repository }}) 